#!/usr/bin/env dart
/// Converts a JSON grammar file (from compile_grammar.mjs) to Dart source
/// with const data for LRParser.deserialize().
///
/// Usage: dart run tool/grammar_to_dart.dart <input.json> <lang_name> [output.dart]

import 'dart:convert';
import 'dart:io';

void main(List<String> args) {
  if (args.length < 2) {
    stderr.writeln(
      'Usage: dart run tool/grammar_to_dart.dart <input.json> <lang_name> [output.dart]',
    );
    exit(1);
  }

  final inputFile = args[0];
  final langName = args[1];
  final outputFile =
      args.length > 2 ? args[2] : 'lib/src/grammars/${langName}_lr.g.dart';

  final json =
      jsonDecode(File(inputFile).readAsStringSync()) as Map<String, dynamic>;

  final nodeNames = (json['nodeNames'] as List).cast<String>();
  final states = (json['states'] as List).cast<int>();
  final stateData = (json['stateData'] as List).cast<int>();
  final gotoTable = (json['goto'] as List).cast<int>();
  final tokenData = (json['tokenData'] as List).cast<int>();
  final topRuleIndex = json['topRuleIndex'] as int;
  final skippedNodes =
      (json['skippedNodes'] as List?)?.cast<int>() ?? <int>[];
  final tokenPrec = json['tokenPrec'] as int? ?? 0;
  final nodeProps = json['nodeProps'] as Map<String, dynamic>? ?? {};

  final buf = StringBuffer()
    ..writeln('// GENERATED FILE — do not edit by hand.')
    ..writeln('// Generated by: dart run tool/grammar_to_dart.dart')
    ..writeln('// Source: $inputFile')
    ..writeln()
    ..writeln("import '../lezer/common/node_type.dart';")
    ..writeln("import '../lezer/lr/lr_parser.dart';")
    ..writeln();

  // Node names
  buf.writeln('const _nodeNames = <String>[');
  for (final name in nodeNames) {
    buf.writeln("  '${_escape(name)}',");
  }
  buf.writeln('];');
  buf.writeln();

  // Int lists
  _writeIntList(buf, '_states', states);
  _writeIntList(buf, '_stateData', stateData);
  _writeIntList(buf, '_goto', gotoTable);
  _writeIntList(buf, '_tokenData', tokenData);

  if (skippedNodes.isNotEmpty) {
    _writeIntList(buf, '_skippedNodes', skippedNodes);
  }

  // Node props
  if (nodeProps.isNotEmpty) {
    buf.writeln('const _nodeProps = <int, Map<NodeProp<dynamic>, dynamic>>{');
    for (final entry in nodeProps.entries) {
      final props = entry.value as Map<String, dynamic>;
      final parts = <String>[];
      if (props['top'] == true) parts.add('NodeProp.top: true');
      if (props['error'] == true) parts.add('NodeProp.error: true');
      if (props['skipped'] == true) parts.add('NodeProp.skipped: true');
      buf.writeln('  ${entry.key}: {${parts.join(', ')}},');
    }
    buf.writeln('};');
  } else {
    buf.writeln('const _nodeProps = <int, Map<NodeProp<dynamic>, dynamic>>{};');
  }
  buf.writeln();

  // Parser
  final camel = langName[0].toLowerCase() + langName.substring(1);
  buf.writeln('/// LR parser for $langName, deserialized from compiled grammar tables.');
  buf.writeln('final ${camel}LRParser = LRParser.deserialize(');
  buf.writeln('  nodeNames: _nodeNames,');
  buf.writeln('  states: _states,');
  buf.writeln('  stateData: _stateData,');
  buf.writeln('  gotoTable: _goto,');
  buf.writeln('  tokenData: _tokenData,');
  buf.writeln('  topRuleIndex: $topRuleIndex,');
  buf.writeln('  nodeProps: _nodeProps,');
  if (skippedNodes.isNotEmpty) buf.writeln('  skippedNodes: _skippedNodes,');
  if (tokenPrec != 0) buf.writeln('  tokenPrec: $tokenPrec,');
  buf.writeln(');');

  final output = File(outputFile);
  output.parent.createSync(recursive: true);
  output.writeAsStringSync(buf.toString());

  stdout.writeln('Generated $outputFile');
  stdout.writeln('  ${nodeNames.length} node types, ${states.length} states');
}

void _writeIntList(StringBuffer buf, String name, List<int> data) {
  buf.writeln('const $name = <int>[');
  for (var i = 0; i < data.length; i += 20) {
    final end = (i + 20).clamp(0, data.length);
    buf.writeln('  ${data.sublist(i, end).join(', ')},');
  }
  buf.writeln('];');
  buf.writeln();
}

String _escape(String s) =>
    s.replaceAll(r'\', r'\\').replaceAll("'", r"\'");
